"use client";
import { createContext, useContext, useEffect, useState } from "react";

const DICT = {
  fr: {
    brand: "LayaliCosmétique",
    shop: "Boutique",
    categories: "Catégories",
    help: "Aide",
    legal: "Mentions",
    account: "Mon compte",
    signin: "Connexion",
    signup: "Créer un compte",
    signout: "Déconnexion",
    cart: "Panier",
    cartEmpty: "Panier vide",
    heroTitle: "Parfums Musc, Autobronzants & Accessoires",
    heroSubtitle: "Beauté sensorielle à prix doux.",
    bestSellers: "Meilleures ventes",
    discover: "Découvrir",
    whyUs: "Pourquoi choisir LayaliCosmétique ?",
    why1: "Qualité premium",
    why1d: "Nos formules sont testées et approuvées.",
    why2: "Prix imbattables",
    why2d: "Moins cher que la concurrence, sans compromis.",
    why3: "Expédition rapide",
    why3d: "Livraison 2–5 jours ouvrés, suivi inclus.",
    catMusc: "Musc",
    catTan: "Autobronzants",
    catAcc: "Accessoires",
    reviews: "Avis clients",
    faq: "Questions fréquentes",
    about: "Qui sommes-nous ?",
    aboutTxt:
      "LayaliCosmétique est une marque française indépendante. Notre mission : rendre accessibles des produits de haute qualité — muscs, autobronzants et accessoires — au meilleur prix, sans compromis sur la sécurité, la composition et l’expérience sensorielle.",
    moreInfo: "En savoir plus",
    shippingInfo: "Adresse de livraison demandée au paiement.",
    details: "Détails",
    deliveryEstimate: "Livraison estimée",
    days: "2–5 jours ouvrés",
    category_MUSC: "MUSC",
    category_LENTILLE: "LENTILLE",
    category_AUTOBRONZANT: "AUTOBRONZANT",
    category_AUTOBRONZANT_VISAGE: "AUTOBRONZANT VISAGE",
    category_ACCESSOIRES: "ACCESSOIRES",
    size_musc: "10 ml",
    size_tan: "200 ml",
    size_tan_face: "100 ml",
  },
  en: {
    brand: "LayaliCosmetics",
    shop: "Shop",
    categories: "Categories",
    help: "Help",
    legal: "Legal",
    account: "My account",
    signin: "Sign in",
    signup: "Create account",
    signout: "Sign out",
    cart: "Cart",
    cartEmpty: "Cart empty",
    heroTitle: "Musk Perfumes, Self-tanners & Accessories",
    heroSubtitle: "Sensorial beauty at fair prices.",
    bestSellers: "Best sellers",
    discover: "Explore",
    whyUs: "Why choose LayaliCosmetics?",
    why1: "Premium quality",
    why1d: "Formulas tested & approved.",
    why2: "Unbeatable prices",
    why2d: "Lower than competitors, no compromise.",
    why3: "Fast shipping",
    why3d: "2–5 business days with tracking.",
    catMusc: "Musk",
    catTan: "Self-tanners",
    catAcc: "Accessories",
    reviews: "Customer reviews",
    faq: "FAQ",
    about: "About us",
    aboutTxt:
      "LayaliCosmetics is a French independent brand. Our mission: deliver high-quality musk, self-tanners and accessories at the best price — with strict safety and delightful sensoriality.",
    moreInfo: "Learn more",
    shippingInfo: "Shipping address requested at checkout.",
    details: "Details",
    deliveryEstimate: "Estimated delivery",
    days: "2–5 business days",
    category_MUSC: "MUSK",
    category_LENTILLE: "LENS",
    category_AUTOBRONZANT: "SELF-TANNER",
    category_AUTOBRONZANT_VISAGE: "FACE SELF-TANNER",
    category_ACCESSOIRES: "ACCESSORIES",
    size_musc: "10 ml",
    size_tan: "200 ml",
    size_tan_face: "100 ml",
  },
  es: {
    brand: "LayaliCosmética",
    shop: "Tienda",
    categories: "Categorías",
    help: "Ayuda",
    legal: "Aviso legal",
    account: "Mi cuenta",
    signin: "Conectar",
    signup: "Crear cuenta",
    signout: "Salir",
    cart: "Carrito",
    cartEmpty: "Carrito vacío",
    heroTitle: "Perfumes de Almizcle, Autobronceadores y Accesorios",
    heroSubtitle: "Belleza sensorial a buen precio.",
    bestSellers: "Más vendidos",
    discover: "Descubrir",
    whyUs: "¿Por qué elegir LayaliCosmética?",
    why1: "Calidad premium",
    why1d: "Fórmulas probadas y aprobadas.",
    why2: "Precio imbatible",
    why2d: "Más barato que la competencia, sin compromisos.",
    why3: "Envío rápido",
    why3d: "2–5 días hábiles con seguimiento.",
    catMusc: "Almizcle",
    catTan: "Autobronceadores",
    catAcc: "Accesorios",
    reviews: "Opiniones",
    faq: "Preguntas frecuentes",
    about: "¿Quiénes somos?",
    aboutTxt:
      "LayaliCosmética es una marca francesa independiente. Nuestra misión: ofrecer almizcles, autobronceadores y accesorios de alta calidad al mejor precio — con seguridad y una experiencia sensorial cuidada.",
    moreInfo: "Saber más",
    shippingInfo: "Dirección de envío en el pago.",
    details: "Detalles",
    deliveryEstimate: "Entrega estimada",
    days: "2–5 días laborables",
    category_MUSC: "ALMIZCLE",
    category_LENTILLE: "LENTE",
    category_AUTOBRONZANT: "AUTOBRONCEADOR",
    category_AUTOBRONZANT_VISAGE: "AUTOBRONCEADOR ROSTRO",
    category_ACCESSOIRES: "ACCESORIOS",
    size_musc: "10 ml",
    size_tan: "200 ml",
    size_tan_face: "100 ml",
  },
};

const LangCtx = createContext({ t: DICT.fr, lang: "fr", setLang: () => {} });

export function LangProvider({ children }) {
  const [lang, setLang] = useState("fr");
  useEffect(() => {
    const saved = typeof window !== "undefined" && localStorage.getItem("lang");
    if (saved && DICT[saved]) setLang(saved);
  }, []);
  useEffect(() => {
    if (typeof window !== "undefined") localStorage.setItem("lang", lang);
  }, [lang]);
  return <LangCtx.Provider value={{ lang, setLang, t: DICT[lang] }}>{children}</LangCtx.Provider>;
}

export function useLang() { return useContext(LangCtx); }
